MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN_ONLY: True
  FCOS_ON: True
  FCOS_MASK: True
  PARSING_ON: True
  FASTER_ON: True
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  MASK_ON: False
  MASKIOU_ON: False
  FCOS:
    CENTER_SAMPLE: True
    POS_RADIUS: 1.5
    LOC_LOSS_TYPE: "giou"
    INFERENCE_TH: 0.03
AIParsing:
  ROI_PARSING_HEAD: "roi_context_head"
  NUM_PARSING: 20
  ROI_STRIDES: [8]
  ROI_SIZE_PER_IMG: 16
  ROI_XFORM_RESOLUTION: (32, 32)
  ROI_XFORM_SAMPLING_RATIO: 2
  RESOLUTION: (256, 256)
  LOSS_WEIGHT: 2.0  # double loss weight
  PARSINGIOU_ON: True
  Context_HEAD:
    NUM_CONVS_AFTER: 4
    USE_NL: True
  PARSINGIOU:
    CONV_DIM: 128
    MLP_DIM: 256
DATASETS:
  TRAIN: ("CIHP_train",)
  TEST: ("CIHP_val",)
INPUT:
  MIN_SIZE_RANGE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.004
  WEIGHT_DECAY: 0.0001
  STEPS: (360000, 480000)
  MAX_ITER: 540000
  IMS_PER_BATCH: 4
  WARMUP_METHOD: "constant"
OUTPUT_DIR : 'checkpoints/CIHP_R50_75epoch'
