MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d"
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET"
  RESNETS:
    STRIDE_IN_1X1: False
    BACKBONE_OUT_CHANNELS: 256
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  RPN_ONLY: True
  FCOS_ON: True
  FCOS_MASK: True
  PARSING_ON: True
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  MASK_ON: False
  MASKIOU_ON: False
  FASTER_ON: False
  FCOS:
    CENTER_SAMPLE: True
    POS_RADIUS: 1.5
    LOC_LOSS_TYPE: "giou"
    INFERENCE_TH: 0.03
AIParsing:
  ROI_PARSING_HEAD: "roi_context_head"
  NUM_PARSING: 59
  ROI_STRIDES: [8]
  ROI_SIZE_PER_IMG: 16
  ROI_XFORM_RESOLUTION: (32, 32)
  ROI_XFORM_SAMPLING_RATIO: 2
  RESOLUTION: (256, 256)
  LOSS_WEIGHT: 2.0  # double loss weight
  PARSINGIOU_ON: True
  SEMSEG_SCORE_THRESH: 0.005
  Context_HEAD:
    NUM_CONVS_AFTER: 4
    USE_NL: True
  PARSINGIOU:
    CONV_DIM: 128
    MLP_DIM: 256

DATASETS:
  TRAIN: ("LV-MHP-v2_train",)
  TEST: ("LV-MHP-v2_val",)
INPUT:
  MIN_SIZE_RANGE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.004
  WEIGHT_DECAY: 0.0001
  STEPS: (130000, 173000)
  MAX_ITER: 200000
  IMS_PER_BATCH: 6
  WARMUP_METHOD: "constant"
OUTPUT_DIR : 'checkpoints/LV-R101-75epoch-IoUloss-IoUscore-parsing6-v100'
